### ISSUE TITLE
A comment turns off subsequent SASS highlighting

### ISSUE THREAD

**Issue by Bill** [aussiegeek/ruby-sass-tmbundle#1]
This SASS does not get highlighted. Removing the comment on the first line, makes highlighting work again.

<pre>
<code>
//
=featured
  color = !featured_text_color
</code>
</pre>

**Comment by cannikin** [comment]
There are two things you can do to fix this:
- Insert a blank line after your comment and highlighting will turn back on
- Edit the bundle:  change line 163 where it tells the bundle what to consider the end of the comment block.  '^$' means a blank line, changing it to '$' means the end of the current line.

**Comment by charlesroper** [comment]
Removing the caret as you suggest works, but it causes for nested 'loud comments' to no longer get scoped as a comment. Do you know what would be required to get them scoped as comments also? The start pattern would be slash followed by a star and the end pattern would be the first line encountered that is NOT indented.

**Comment by charlesroper** [comment]
^(?! ) did the trick: http://github.com/charlesr/ruby-sass-tmbundle/commit/73556bf7b45edbdad89c42bb09552dbc10421ec2

I've pushed this fix to my fork; will also issue a pull request.

**Comment by Bill** [comment]
Well I think that improves the situation. However this still does not get highlighted:

```
//
  =featured
    color = !featured_text_color
```

If I indent that comment (to match the indention of the subsequent macro definition) the highlighting lights up.

**Comment by charlesroper** [comment]
Have you tried the latest updates on my fork that incorporate fixes by Matt Pizzimenti @mjpizz?

**Comment by Bill** [comment]
I just did this:
    git clone git://github.com/charlesr/ruby-sass-tmbundle.git "Ruby Sass.tmbundle"
And can confirm that the example above is still broken. For example, this does not highlight:
    // foo
      a
        color: red

**Comment by cannikin** [comment]
Everything should be a gray comment in that example. Indenting beneath a comment makes everything indented a comment.

In this example, everything under the comment should NOT be highlighted as a comment (but is, even with charlesr's fork):

```
/ foo
a
  color: red
```

**Comment by Bill** [comment]
Gracious! You're right. That is so wierd. But you've fixed a bug in my code. Thanks!

http://sass-lang.com/docs/yardoc/SASS_REFERENCE.md.html#sass_comments_

**Comment by cannikin** [comment]
You're welcome! :) Yeah, if you follow the SASS bundle then you'll think things are commented out when they're not.  I hope someone repairs the bundle to show what is truly considered a comment by the SASS engine (the entire line that contains a comment and anything that is indented under that comment ONLY).

**Comment by charlesroper** [comment]
@cannikin, in your example there's only one slash before the 'foo' - is that a typo or did you intend it that way? That example is working fine for me in E Text Editor - everything under the comment is _not_ being highlighted.

I've pushed another update to my fork because I noticed CSS 'loud comments' no longer worked. I've also updated the testhighlight.sass file to reflect the examples in the Sass docs. For me in E, everything is highlighting as it should. Would appreciate feedback on what it looks like in TM. Cheers.

**Comment by charlesroper** [comment]
I've updated the testhighlight.sass file and checked the highlighting in both E and Sublime and both work as expected. I think we can close this unless there are still problems on TM?

**Comment by Bill** [comment]
@charlesr are you the new maintainer @ausiegeek asked for? If so then I agree we can close this, otherwise I move we keep it open until the fix is migrated to the maintainer's repo.

**Comment by cannikin** [comment]
Yep, things look good for me, close away!

**Comment by charlesroper** [comment]
@Bill, good point, @aussiegeek hasn't merged in the fixes yet.

**Comment by arta** [comment]
Hmm, nobody uses one-line comments following the declaration, which .css allows? (and http://github.com/seaofclouds/sass-textmate-bundle does too.) I use them on occasion:

```
.selector
  property: value /* comment */
```
